sudo: required
services:
  - docker
before_install:
  - docker build -t guibastos/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true guibastos/react-test npm run test -- --coverage
after_success:
  - docker build -t guibastos/multi-client ./client
  - docker build -t guibastos/multi-nginx ./nginx
  - docker build -t guibastos/multi-server ./server
  - docker build -t guibastos/multi-worker ./worker
  # Log in to the docker CLI.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push guibastos/multi-client
  - docker push guibastos/multi-nginx
  - docker push guibastos/multi-server
  - docker push guibastos/multi-worker
